version: "3.9"
services:
  dev:
    image: pytorch/pytorch:latest 
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - 0.0.0.0:54311:8889
    environment:
      - TZ=Asia/Seoul
      - DEBIAN_FRONTEND=noninteractive
    shm_size: "32gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["3"]
              capabilities: [gpu]
    stdin_open: true
